import fs from "node:fs";
import path from "node:path";
import fg from "fast-glob";
import {
  buildDefaultArgs,
  getTideDir,
  getManifestPath,
  getPropsPath,
  getStoriesPath,
  type TideConfig,
  type Manifest,
  type PropsMap,
} from "@tide/core";
import { discoverComponents } from "./discover.js";
import { extractProps } from "./extract-props.js";

export interface GenerateResult {
  manifest: Manifest;
  props: PropsMap;
  storiesPath: string;
}

export async function generateArtifacts(config: TideConfig): Promise<GenerateResult> {
  const { root, scan } = config;
  const tideDir = getTideDir(root);
  fs.mkdirSync(tideDir, { recursive: true });

  const files = await fg(scan.include, { cwd: root, absolute: false });
  const components = discoverComponents(root, files);
  const props = extractProps(root, components);
  const manifest: Manifest = { components };

  fs.writeFileSync(getManifestPath(root), JSON.stringify(manifest, null, 2));
  fs.writeFileSync(getPropsPath(root), JSON.stringify(props, null, 2));

  const storiesContent = generateStoriesFile(root, manifest, props);
  const storiesPath = getStoriesPath(root);
  fs.writeFileSync(storiesPath, storiesContent);

  if (config.tokens) {
    const tokensSrc = path.isAbsolute(config.tokens)
      ? config.tokens
      : path.join(root, config.tokens);
    if (fs.existsSync(tokensSrc)) {
      fs.copyFileSync(tokensSrc, path.join(tideDir, "tokens.json"));
    }
  }

  return { manifest, props, storiesPath };
}

function generateStoriesFile(root: string, manifest: Manifest, props: PropsMap): string {
  const lines: string[] = ["// Auto-generated by Tide — do not edit", ""];

  const imports: string[] = [];
  const storyEntries: string[] = [];

  for (const component of manifest.components) {
    const tideDir = path.join(root, ".tide");
    const relImport = path.relative(tideDir, path.join(root, component.path)).replace(/\\/g, "/");
    const importPath = relImport.startsWith(".") ? relImport : `./${relImport}`;
    const importId = `_${component.name}`;
    imports.push(`import * as ${importId} from ${JSON.stringify(importPath)};`);

    const componentProps = props[component.name] ?? {};
    const args = buildDefaultArgs(componentProps);
    const argsJson = JSON.stringify(args, null, 2).split("\n").join("\n    ");

    const exportKey = component.isDefault ? "default" : component.exportName;
    storyEntries.push(`  ${JSON.stringify(component.name)}: {
    load: () => Promise.resolve(${importId}),
    exportName: ${JSON.stringify(exportKey)},
    isDefault: ${component.isDefault ?? false},
    args: ${argsJson},
    title: ${JSON.stringify(component.title)},
    path: ${JSON.stringify(component.path)},
  }`);
  }

  lines.push(...imports);
  lines.push("");
  lines.push("export const stories = {");
  lines.push(storyEntries.join(",\n"));
  lines.push("};");
  lines.push("");
  lines.push("export type StoryName = keyof typeof stories;");

  return lines.join("\n");
}

export { discoverComponents } from "./discover.js";
export { extractProps } from "./extract-props.js";
