import fs from "node:fs";
import path from "node:path";
import fg from "fast-glob";
import {
  buildDefaultArgs,
  getComponentId,
  getConfigSnapshotPath,
  getManifestPath,
  getPropsPath,
  getScanReportPath,
  getStoriesPath,
  getBindingsPath,
  getTidexDir,
  DEFAULT_SCAN_EXCLUDE,
  type TidexConfig,
  type Manifest,
  type PropsMap,
} from "@tidex/core";
import { discoverComponents } from "./discover.js";
import { extractProps } from "./extract-props.js";
import { inferInteractions } from "./infer-interactions.js";
import {
  buildScanDiagnostics,
  formatScanDiagnostics,
  type ScanDiagnostics,
} from "./diagnostics.js";

export interface GenerateResult {
  manifest: Manifest;
  props: PropsMap;
  storiesPath: string;
  diagnostics: ScanDiagnostics;
}

export interface GenerateOptions {
  verbose?: boolean;
  /** Reports prop-extraction progress (the slow phase) as `(done, total, label)`. */
  onProgress?: (done: number, total: number, label?: string) => void;
}

let warnedFallback = false;
function warnFallbackOnce(include: string[], root: string, count: number) {
  if (warnedFallback) return;
  warnedFallback = true;
  console.warn(
    `[tidex] scan.include ${JSON.stringify(include)} matched no files under ${root}; ` +
      `scanning "**/*.tsx" instead (${count} files). ` +
      `Add scan.include to tidex.config.ts to silence this.`,
  );
}

export async function generateArtifacts(
  config: TidexConfig,
  options: GenerateOptions = {},
): Promise<GenerateResult> {
  const { root, scan } = config;
  const tidexDir = getTidexDir(root);
  fs.mkdirSync(tidexDir, { recursive: true });

  const ignore = [...DEFAULT_SCAN_EXCLUDE, ...(scan.exclude ?? [])];
  let files = await fg(scan.include, { cwd: root, absolute: false, ignore });

  if (files.length === 0) {
    const fallback = await fg(["**/*.tsx"], { cwd: root, absolute: false, ignore });
    if (fallback.length > 0) {
      warnFallbackOnce(scan.include, root, fallback.length);
      files = fallback;
    }
  }

  const components = discoverComponents(root, files, {
    componentsDir: scan.componentsDir,
  });
  const props = await extractProps(root, components, options.onProgress);
  const manifest: Manifest = { components };
  const diagnostics = buildScanDiagnostics(files, components, props);

  // Infer interaction bindings (state prop ↔ change handler) so the preview can
  // wire itself interactive automatically.
  const bindings = inferInteractions(root, components, props);

  fs.writeFileSync(getManifestPath(root), JSON.stringify(manifest, null, 2));
  fs.writeFileSync(getPropsPath(root), JSON.stringify(props, null, 2));
  fs.writeFileSync(getBindingsPath(root), JSON.stringify(bindings, null, 2));
  fs.writeFileSync(getScanReportPath(root), JSON.stringify(diagnostics, null, 2));
  fs.writeFileSync(
    getConfigSnapshotPath(root),
    JSON.stringify(
      {
        packageName: config.packageName ?? null,
        defaults: config.defaults ?? {},
        componentsDir: scan.componentsDir ?? null,
      },
      null,
      2,
    ),
  );

  const storiesContent = generateStoriesFile(root, manifest, props, config);
  const storiesPath = getStoriesPath(root);
  fs.writeFileSync(storiesPath, storiesContent);

  if (config.tokens) {
    const tokensSrc = path.isAbsolute(config.tokens)
      ? config.tokens
      : path.join(root, config.tokens);
    if (fs.existsSync(tokensSrc)) {
      fs.copyFileSync(tokensSrc, path.join(tidexDir, "tokens.json"));
    }
  }

  if (options.verbose) {
    console.log(formatScanDiagnostics(diagnostics));
  }

  return { manifest, props, storiesPath, diagnostics };
}

function generateStoriesFile(
  root: string,
  manifest: Manifest,
  props: PropsMap,
  config: TidexConfig,
): string {
  const lines: string[] = ["// Auto-generated by Tidex — do not edit", ""];

  const imports: string[] = [];
  const storyEntries: string[] = [];

  const tidexDirAbs = path.join(root, ".tidex");
  let wrapperExport = "export const previewWrapper = null;";
  const wrapper = config.preview?.wrapper;
  if (wrapper) {
    const abs = path.isAbsolute(wrapper) ? wrapper : path.join(root, wrapper);
    const rel = path.relative(tidexDirAbs, abs).replace(/\\/g, "/");
    const importPath = rel.startsWith(".") ? rel : `./${rel}`;
    imports.push(`import __previewWrapper from ${JSON.stringify(importPath)};`);
    wrapperExport = "export const previewWrapper = __previewWrapper;";
  }

  for (const component of manifest.components) {
    const componentId = getComponentId(component);
    const relImport = path
      .relative(tidexDirAbs, path.join(root, component.path))
      .replace(/\\/g, "/");
    const importPath = relImport.startsWith(".") ? relImport : `./${relImport}`;

    const componentProps = props[componentId] ?? {};
    const args = buildDefaultArgs(componentProps, config.defaults?.[componentId]);
    const argsJson = JSON.stringify(args, null, 2).split("\n").join("\n    ");

    const exportKey = component.isDefault ? "default" : component.exportName;
    storyEntries.push(`  ${JSON.stringify(componentId)}: {
    load: () => import(${JSON.stringify(importPath)}),
    exportName: ${JSON.stringify(exportKey)},
    isDefault: ${component.isDefault ?? false},
    args: ${argsJson},
    title: ${JSON.stringify(component.title)},
    path: ${JSON.stringify(component.path)},
    name: ${JSON.stringify(component.name)},
  }`);
  }

  lines.push(...imports);
  lines.push("");
  lines.push("export const stories = {");
  lines.push(storyEntries.join(",\n"));
  lines.push("};");
  lines.push("");
  lines.push(wrapperExport);
  lines.push("");
  lines.push("export type StoryName = keyof typeof stories;");

  return lines.join("\n");
}

export { discoverComponents } from "./discover.js";
export { extractProps } from "./extract-props.js";
export { inferInteractions, inferComponentBindings } from "./infer-interactions.js";
export {
  buildScanDiagnostics,
  formatScanDiagnostics,
  type ScanDiagnostics,
} from "./diagnostics.js";
